# TCONTRACTS

TCONTRACTS_ADD = INSERT INTO TContracts(mechanic_id, contractType_id, \
	professionalGroup_id, annualBaseSalary, id, version, createdAt, updatedAt, entityState, settlement, startdate, state, taxrate) \
	VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
TCONTRACTS_DELETE = DELETE FROM TCONTRACTS WHERE ID = ?
TCONTRACTS_UPDATE = update TContracts \
	set endDate = ?, annualBaseSalary = ?, version = version+1, \
	updatedat = ?, state = ?, settlement = ? where id = ?
TCONTRACTS_FINDBYID = SELECT ID, VERSION, STATE, ENDDATE, CREATEDAT, UPDATEDAT, ENTITYSTATE, ANNUALBASESALARY, contractType_id, \
	MECHANIC_ID, PROFESSIONALGROUP_ID, SETTLEMENT, STARTDATE, TAXRATE FROM TCONTRACTS WHERE ID = ?
	TCONTRACTS_FINDALL = SELECT ID, VERSION, STATE, ENDDATE, CREATEDAT, UPDATEDAT, ENTITYSTATE, ANNUALBASESALARY, contractType_id, MECHANIC_ID, \
	PROFESSIONALGROUP_ID, SETTLEMENT, STARTDATE, TAXRATE FROM TCONTRACTS
TCONTRACTS_FIND_BY_MECHANIC_ID = SELECT ID, VERSION, STATE, ENDDATE, CREATEDAT, UPDATEDAT, ENTITYSTATE, ANNUALBASESALARY, \
	contractType_id, MECHANIC_ID, PROFESSIONALGROUP_ID, SETTLEMENT, STARTDATE, TAXRATE FROM TCONTRACTS WHERE MECHANIC_ID = ?
TCONTRACTS_FIND_IN_FORCE_CONTRACT_BY_MECHANIC_ID = SELECT ID, VERSION, STATE, ENDDATE, CREATEDAT, UPDATEDAT, ENTITYSTATE, \
	ANNUALBASESALARY, contractType_id, MECHANIC_ID, PROFESSIONALGROUP_ID, SETTLEMENT, STARTDATE, TAXRATE FROM TCONTRACTS WHERE MECHANIC_ID = ? AND STATE = 'IN_FORCE'
TCONTRACTS_FIND_MECHANIC_ID_BY_CONTRACT_ID = SELECT MECHANIC_ID FROM TCONTRACTS WHERE ID = ?
TCONTRACTS_FIND_ALL_BETWEEN = SELECT ID, VERSION, STATE, ENDDATE, CREATEDAT, UPDATEDAT, ENTITYSTATE, \
	ANNUALBASESALARY, contractType_id, MECHANIC_ID, PROFESSIONALGROUP_ID, SETTLEMENT, STARTDATE, \
	TAXRATE FROM TCONTRACTS WHERE startDate <= ? AND (state='IN_FORCE' OR endDate >= ?)
TCONTRACTS_EXISTS_FOR_PROFESSIONAL_GROUP = SELECT ID FROM TCONTRACTS T JOIN TPROFESSIONALGROUPS P \
	ON T.PROFESSIONALGROUP_ID = P.ID WHERE P.NAME = ?

# TCONTRACTTYPES

TCONTRACTTYPES_ADD = INSERT INTO TCONTRACTTYPES (id, compensationDaysPerYear, version, updatedAt, createdAt, entityState, name) \
	values (?,?,?,?,?,?,?)
TCONTRACTTYPES_DELETE = DELETE FROM TCONTRACTTYPES WHERE NAME = ?
TCONTRACTTYPES_UPDATE = update TContracttypes \
	set compensationDaysPerYear = ?, version = version+1, \
	updatedat = ? where id = ?
TCONTRACTTYPES_FINDBYID = SELECT ID, NAME, VERSION, CREATEDAT, UPDATEDAT, ENTITYSTATE, COMPENSATIONDAYSPERYEAR FROM TCONTRACTTYPES WHERE ID = ?
TCONTRACTTYPES_FIND_ALL = SELECT ID, NAME, VERSION, CREATEDAT, UPDATEDAT, ENTITYSTATE, COMPENSATIONDAYSPERYEAR FROM TCONTRACTTYPES
TCONTRACTTYPES_FINDBYNAME = SELECT ID, NAME, VERSION, CREATEDAT, UPDATEDAT, ENTITYSTATE, COMPENSATIONDAYSPERYEAR FROM TCONTRACTTYPES WHERE NAME = ?
                               
# TINTERVENTIONS

TINTERVENTIONS_FIND_BY_MECHANIC_ID = SELECT ID FROM TINTERVENTIONS WHERE MECHANIC_ID = ?

# TINVOICES

TINVOICES_ADD = INSERT INTO TInvoices(id, number, date, vat, amount, state, version, createdAt, updatedAt, entityState) \
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
TINVOICES_FINDBYID = SELECT ID, VERSION, AMOUNT, VAT, STATE, NUMBER, DATE, CREATEDAT, UPDATEDAT, ENTITYSTATE FROM TINVOICES WHERE ID = ?
TINVOICES_SELECT_LAST_NUMBER = SELECT MAX(number) FROM TInvoices
TINVOICES_FINDNEXTNUMBER = SELECT MAX(number) FROM TInvoices

# TMECHANICS

TMECHANICS_ADD = insert into TMechanics(id, nif, name, surname, version, \
	createdAt, updatedAt, entityState) \
	values (?, ?, ?, ?, ?, ?, ?, ?)
TMECHANICS_DELETE = delete from TMechanics where id = ?
TMECHANICS_UPDATE = update TMechanics \
	set name = ?, surname = ?, version = version+1, \
	updatedat = ? where id = ?
TMECHANICS_FINDBYID = SELECT ID, NAME, SURNAME, NIF, VERSION, CREATEDAT, UPDATEDAT, ENTITYSTATE FROM TMECHANICS WHERE ID = ?
TMECHANICS_FINDALL = select id, nif, name, surname, version from TMechanics
TMECHANICS_FINDBYNIF = select id, nif, name, surname, version, createdAt, updatedAt, entityState from TMechanics \
	where nif = ?


         
# TPAYROLLS

TPAYROLLS_ADD = INSERT INTO TPayrolls (id, version, createdAt, updatedAt, entityState, baseSalary, \
	extraSalary, productivityEarning, trienniumEarning, taxDeduction, nicDeduction, \
	date, contract_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
TPAYROLLS_REMOVE_DATE_OF = DELETE FROM TPAYROLLS WHERE DATE BETWEEN ? AND ? 
TPAYROLLS_REMOVE_LAST_OF_MECHANIC = DELETE FROM TPayrolls WHERE contract_id IN (SELECT id FROM TContracts WHERE mechanic_id = ?) AND date BETWEEN ? AND ?
TPAYROLLS_FIND_BY_ID = SELECT ID, UPDATEDAT, CREATEDAT, ENTITYSTATE, VERSION, BASESALARY, DATE, NICDEDUCTION, \
	TAXDEDUCTION, TRIENNIUMEARNING, PRODUCTIVITYEARNING, CONTRACT_ID, EXTRASALARY FROM TPAYROLLS WHERE ID = ?
TPAYROLLS_FIND_ALL = SELECT ID, UPDATEDAT, CREATEDAT, ENTITYSTATE, VERSION, BASESALARY, DATE, NICDEDUCTION, \
	TAXDEDUCTION, TRIENNIUMEARNING, PRODUCTIVITYEARNING, CONTRACT_ID, EXTRASALARY FROM TPAYROLLS
TPAYROLLS_GROSS_SALARY_OF_THE_LAST_YEAR = SELECT COALESCE(SUM(baseSalary + extraSalary + productivityEarning + trienniumEarning), 0) \
	FROM TPayrolls WHERE contract_id = ? AND date BETWEEN ? AND ?
TPAYROLLS_FIND_BY_CONTRACT_ID = SELECT ID FROM TPAYROLLS WHERE CONTRACT_ID = ?
TPAYROLLS_EXISTS_PAYROLL_FOR_CONTRACT_IN_DATE = SELECT ID FROM TPAYROLLS WHERE DATE = ? AND CONTRACT_ID = ?              
TPAYROLLS_FIND_BY_MECHANIC_ID = SELECT ID, UPDATEDAT, CREATEDAT, ENTITYSTATE, VERSION, BASESALARY, DATE, NICDEDUCTION, \
	TAXDEDUCTION, TRIENNIUMEARNING, PRODUCTIVITYEARNING, CONTRACT_ID, EXTRASALARY FROM TPAYROLLS P JOIN \
	TCONTRACTS C ON P.CONTRACT_ID = C.ID WHERE C.MECHANIC_ID = ?
TPAYROLLS_FIND_BY_PROFESSIONALGROUP_NAME = SELECT ID, UPDATEDAT, CREATEDAT, ENTITYSTATE, VERSION, BASESALARY, DATE, NICDEDUCTION, \
	TAXDEDUCTION, TRIENNIUMEARNING, PRODUCTIVITYEARNING, CONTRACT_ID, EXTRASALARY FROM TPAYROLLS P JOIN \
	TCONTRACTS C ON P.CONTRACT_ID = C.ID JOIN TPROFESSIONALGROUPS PG ON PG.ID = C.PROFESSIONALGROUP_ID \
	WHERE PG.NAME = ?

# TPROFESSIONALGROUPS

TPROFESSIONALGROUPS_ADD = INSERT INTO TProfessionalGroups (id, version, createdAt, updatedAt, entityState, name, productivityRate, trienniumPayment) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
TPROFESSIONALGROUPS_REMOVE = DELETE FROM TProfessionalGroups WHERE name = ?
TPROFESSIONALGROUPS_UPDATE = UPDATE TProfessionalGroups SET productivityRate = ?, trienniumPayment = ?, updatedAt = ?, version = ? WHERE id = ?
TPROFESSIONALGROUPS_FINDBYID = SELECT ID, VERSION, CREATEDAT, UPDATEDAT, ENTITYSTATE, NAME, PRODUCTIVITYRATE, TRIENNIUMPAYMENT FROM TPROFESSIONALGROUPS WHERE ID = ?                    
TPROFESSIONALGROUPS_FIND_ALL = SELECT ID, VERSION, CREATEDAT, UPDATEDAT, ENTITYSTATE, NAME, PRODUCTIVITYRATE, TRIENNIUMPAYMENT FROM TPROFESSIONALGROUPS
TPROFESSIONALGROUPS_FINDBYNAME = SELECT ID, VERSION, CREATEDAT, UPDATEDAT, ENTITYSTATE, NAME, PRODUCTIVITYRATE, TRIENNIUMPAYMENT FROM TPROFESSIONALGROUPS WHERE NAME = ?  
                 
           
# TWORKORDERS

TWORKORDERS_UPDATE = UPDATE TWorkOrders SET description = ?, state = ?, updatedAt = ?, mechanic_id = ?, vehicle_id = ?, amount = ?, version = version + 1 WHERE id = ?
TWORKORDERS_FIND_BY_ID = SELECT id, version, createdAt, updatedAt, entityState, date, description, amount, state, mechanic_id, vehicle_id, invoice_id FROM TWorkOrders WHERE id = ?
TWORKORDERS_FIND_NOT_INVOICED = select a.id, a.description, a.date, a.state, a.amount from TWorkOrders as a, \
	TVehicles as v, TClients as c \
	where a.vehicle_id = v.id \
	and v.client_id = c.id \
	and state like 'FINISHED' \
	and nif like ?
TWORKORDERS_EXISTS_WORKORDERS_FOR_MECHANIC_ID = SELECT ID FROM TWORKORDERS WHERE MECHANIC_ID = ?
TWORKORDERS_FIND_AMOUNT_BETWEEN = SELECT COALESCE(SUM(w.amount), 0.0) FROM TWorkOrders w JOIN TInterventions i ON i.workorder_id = w.id WHERE w.date BETWEEN ? AND ? AND i.mechanic_id = ? AND w.state = 'INVOICED'